export 'package:cloud_firestore/cloud_firestore.dart';
export 'package:firebase_auth/firebase_auth.dart';
export 'package:firebase_core/firebase_core.dart';
export 'package:flutter/foundation.dart' hide kIsWasm;
export 'package:flutter/material.dart';
export 'package:flutter_bloc/flutter_bloc.dart';
export 'package:freezed_annotation/freezed_annotation.dart';
export 'package:get_it/get_it.dart';
export 'package:go_router/go_router.dart';
export 'package:hive_ce/hive_ce.dart';
export 'package:hive_ce_flutter/hive_flutter.dart';
export 'package:intl/intl.dart' hide TextDirection;
export 'package:lottie/lottie.dart';
export 'package:uuid/uuid.dart';

export 'app/xcore.dart';
export 'core/xcore.dart';
export 'firebase_options.dart';
export 'generated/xcore.dart';
export 'shared/xcore.dart';
