// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAK6dOkfV83Jtw3Ooob0wbtY8xDluqciFY',
    appId: '1:909503381680:web:efaa3330e674932f7cfb75',
    messagingSenderId: '909503381680',
    projectId: 'famxpense-tp',
    authDomain: 'famxpense-tp.firebaseapp.com',
    storageBucket: 'famxpense-tp.firebasestorage.app',
    measurementId: 'G-KRQXSM8HV2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZw4FbzwfSG7ArORbpHOFFYPxZH3sScyo',
    appId: '1:909503381680:android:603a018fca0493fe7cfb75',
    messagingSenderId: '909503381680',
    projectId: 'famxpense-tp',
    storageBucket: 'famxpense-tp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQIUzfFm8unRRBsK0Jpl5kJjqDD3UwqD4',
    appId: '1:909503381680:ios:0fb68849e40532a97cfb75',
    messagingSenderId: '909503381680',
    projectId: 'famxpense-tp',
    storageBucket: 'famxpense-tp.firebasestorage.app',
    iosBundleId: 'com.tejasd.famxpense',
  );
}
