// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError('DefaultFirebaseOptions are not supported for this platform.');
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuzuSH_tTFH_4jxnGpbIOPFoKtug7OXlA',
    appId: '1:238098914441:web:a42798b2069326a79eba58',
    messagingSenderId: '238098914441',
    projectId: 'famxpense-tp-dev',
    authDomain: 'famxpense-tp-dev.firebaseapp.com',
    storageBucket: 'famxpense-tp-dev.firebasestorage.app',
    measurementId: 'G-ELNJTPMY8W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCi4LQ0cLJzkuHM4kRQ-OUlmJcqqs75-d0',
    appId: '1:238098914441:android:a7ab69f8de0a66a39eba58',
    messagingSenderId: '238098914441',
    projectId: 'famxpense-tp-dev',
    storageBucket: 'famxpense-tp-dev.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQyxhhk-r1KhxAG2GLyuIMcYm-OJitv98',
    appId: '1:238098914441:ios:f7e4a8a27cfdf8599eba58',
    messagingSenderId: '238098914441',
    projectId: 'famxpense-tp-dev',
    storageBucket: 'famxpense-tp-dev.firebasestorage.app',
    iosBundleId: 'com.tejasd.famxpense.dev',
  );
}
