// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:famxpense/shared/data/transformers/dtos/account/account_dto.dart';
import 'package:famxpense/shared/data/transformers/dtos/account/manual_deposit_dto.dart';
import 'package:famxpense/shared/data/transformers/dtos/debt_ledger/debt_ledger_dto.dart';
import 'package:famxpense/shared/data/transformers/dtos/expense/expense_dto.dart';
import 'package:famxpense/shared/data/transformers/dtos/expense/expense_participant_dto.dart';
import 'package:famxpense/shared/data/transformers/dtos/income/income_dto.dart';
import 'package:famxpense/shared/data/transformers/dtos/notification/notification_dto.dart';
import 'package:famxpense/shared/data/transformers/dtos/partnership/partnership_dto.dart';
import 'package:famxpense/shared/data/transformers/dtos/savings/monthly_saving_dto.dart';
import 'package:famxpense/shared/data/transformers/dtos/settlement/settlement_dto.dart';
import 'package:famxpense/shared/data/transformers/dtos/transfer/transfer_dto.dart';
import 'package:famxpense/shared/data/transformers/dtos/user/user_dto.dart';
import 'package:famxpense/shared/enums/account_type.dart';
import 'package:famxpense/shared/enums/expense_category.dart';
import 'package:famxpense/shared/enums/expense_type.dart';
import 'package:famxpense/shared/enums/income_source.dart';
import 'package:famxpense/shared/enums/notification_type.dart';
import 'package:famxpense/shared/enums/partnership_status.dart';
import 'package:famxpense/shared/enums/settlement_status.dart';
import 'package:famxpense/shared/enums/split_type.dart';
import 'package:famxpense/shared/enums/sync_status.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(AccountDtoAdapter());
    registerAdapter(AccountTypeAdapter());
    registerAdapter(DebtLedgerDtoAdapter());
    registerAdapter(ExpenseCategoryAdapter());
    registerAdapter(ExpenseDtoAdapter());
    registerAdapter(ExpenseParticipantDtoAdapter());
    registerAdapter(ExpenseTypeAdapter());
    registerAdapter(IncomeDtoAdapter());
    registerAdapter(IncomeSourceAdapter());
    registerAdapter(ManualDepositDtoAdapter());
    registerAdapter(MonthlySavingDtoAdapter());
    registerAdapter(NotificationDtoAdapter());
    registerAdapter(NotificationTypeAdapter());
    registerAdapter(PartnershipDtoAdapter());
    registerAdapter(PartnershipStatusAdapter());
    registerAdapter(SettlementDtoAdapter());
    registerAdapter(SettlementStatusAdapter());
    registerAdapter(SplitTypeAdapter());
    registerAdapter(SyncStatusAdapter());
    registerAdapter(TransferDtoAdapter());
    registerAdapter(UserDtoAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(AccountDtoAdapter());
    registerAdapter(AccountTypeAdapter());
    registerAdapter(DebtLedgerDtoAdapter());
    registerAdapter(ExpenseCategoryAdapter());
    registerAdapter(ExpenseDtoAdapter());
    registerAdapter(ExpenseParticipantDtoAdapter());
    registerAdapter(ExpenseTypeAdapter());
    registerAdapter(IncomeDtoAdapter());
    registerAdapter(IncomeSourceAdapter());
    registerAdapter(ManualDepositDtoAdapter());
    registerAdapter(MonthlySavingDtoAdapter());
    registerAdapter(NotificationDtoAdapter());
    registerAdapter(NotificationTypeAdapter());
    registerAdapter(PartnershipDtoAdapter());
    registerAdapter(PartnershipStatusAdapter());
    registerAdapter(SettlementDtoAdapter());
    registerAdapter(SettlementStatusAdapter());
    registerAdapter(SplitTypeAdapter());
    registerAdapter(SyncStatusAdapter());
    registerAdapter(TransferDtoAdapter());
    registerAdapter(UserDtoAdapter());
  }
}
