// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:famxpense/shared/transformers/dtos/account/account_dto.dart';
import 'package:famxpense/shared/transformers/dtos/debt_ledger/debt_ledger_dto.dart';
import 'package:famxpense/shared/transformers/dtos/expense/draft_expense_dto.dart';
import 'package:famxpense/shared/transformers/dtos/expense/expense_dto.dart';
import 'package:famxpense/shared/transformers/dtos/expense/expense_participant_dto.dart';
import 'package:famxpense/shared/transformers/dtos/group/group_dto.dart';
import 'package:famxpense/shared/transformers/dtos/notification/notification_dto.dart';
import 'package:famxpense/shared/transformers/dtos/partnership/partnership_dto.dart';
import 'package:famxpense/shared/transformers/dtos/settlement/settlement_dto.dart';
import 'package:famxpense/shared/transformers/dtos/user/user_dto.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(AccountDtoAdapter());
    registerAdapter(DebtLedgerDtoAdapter());
    registerAdapter(DraftExpenseDtoAdapter());
    registerAdapter(ExpenseDtoAdapter());
    registerAdapter(ExpenseParticipantDtoAdapter());
    registerAdapter(GroupDtoAdapter());
    registerAdapter(NotificationDtoAdapter());
    registerAdapter(PartnershipDtoAdapter());
    registerAdapter(SettlementDtoAdapter());
    registerAdapter(UserDtoAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(AccountDtoAdapter());
    registerAdapter(DebtLedgerDtoAdapter());
    registerAdapter(DraftExpenseDtoAdapter());
    registerAdapter(ExpenseDtoAdapter());
    registerAdapter(ExpenseParticipantDtoAdapter());
    registerAdapter(GroupDtoAdapter());
    registerAdapter(NotificationDtoAdapter());
    registerAdapter(PartnershipDtoAdapter());
    registerAdapter(SettlementDtoAdapter());
    registerAdapter(UserDtoAdapter());
  }
}
